### ISSUE TITLE
where is the database sql?

### ISSUE THREAD

**Issue by smzhao** [a-watkin/flask-photo-site#1]
please . thanks

**Comment by a-watkin** [comment]
You mean to make the tables? In database_interface.py I didn't really envision anyone forking this code so it may not be 100% up to date but you shouldn't be able to tweak it to what you have in mind.

If you mean't to make queries then it's in the various files like photo, tag etc.

**Comment by a-watkin** [comment]
So I was just reading some of my code and I realised that I didn't answer your question correctly. This project was an extension of an earlier one. So the database schema is actually in the link below. It's kind of a mess I'm afraid as it went through several changes.

[Link to schema](https://github.com/a-watkin/flickr-api-transfer/blob/master/database_schema/db_schema.py)
